---
- name: Run installer
  command: "{{ jira_home }}/{{ jira_versions[jira_version]['url']|basename }} -q -varfile {{ jira_home }}/response.varfile"
  become: yes
  become_method: sudo
  become_user: "{{ jira_versions[jira_version]['installer_user']|default('root') }}"
  notify:
    - lcm-version-file
    - jira-systemctl-daemon-reload
    - jira-systemctl-restart
  when: not jira_manual_upgrade
