---
namespace: c2platform
name: atlassian
version: "0.1.2"
readme: README.md
authors:
  - Onno van der Straaten (onno@onknows.com)
license_file: LICENSE

description: C2 Platform Ansible Collection for Atlassian Jira, Confluence, Bitbucket

tags:
  - c2platform
  - atlassian
  - jira
  - confluence
  - bitbucket

dependencies: {}

repository: https://github.com/c2platform/ansible-collection-atlassian
documentation: https://github.com/c2platform/ansible-collection-atlassian
homepage: https://github.com/c2platform/
issues: https://github.com/c2platform/ansible-collection-atlassian/issues

build_ignore: []
