---
- name: bitbucket-systemctl-daemon-reload
  systemd:
    daemon_reload: true
  changed_when: false
  ignore_errors: true

- name: bitbucket-systemctl-restart
  service:
    name: "bitbucket"
    state: "restarted"
    enabled: true
  loop: "{{ ansible_play_hosts }}"
  delegate_to: "{{ item }}"
  run_once: true
  changed_when: false
  ignore_errors: true
