---
- name: Home
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ confluence_home_version }}"
    - "{{ confluence_home_version_home }}"

- name: Create symbolic link install
  file:
    src: "{{ confluence_home_version }}"
    dest: "{{ confluence_home_link }}"
    state: link

- name: response file
  template:
    dest: "{{ confluence_home }}/reponse.varfile"
    src: response.varfile.j2
    mode: 0644

- name: Copy home dir
  command: "rsync -az --delete --recursive --exclude='VERSION' {{ confluence_home_version_current }}/ {{ confluence_home_version }}/"
  when: confluence_lcm['operation'] == 'upgrade'
  notify:
    - lcm-version-file

- include: installer.yml
  when: confluence_lcm['operation'] == 'install'

- include: configure-home.yml

- include: installer.yml
  when: confluence_lcm['operation'] == 'upgrade'

- include: configure-app.yml

- name: chown confluence home version
  file:
    dest: "{{ confluence_home }}"
    owner: "{{ confluence_owner }}"
    group: "{{ confluence_group }}"
    recurse: yes
  when: confluence_lcm['operation'] in ['upgrade','install']

- name: remove installer
  file:
    path: "{{ confluence_home }}/{{ confluence_versions[confluence_version]['url']|basename }}"
    state: absent
  when: confluence_lcm['operation'] not in ['upgrade','install']
