---
- name: add bitbucket owner
  user:
    name: "{{ bitbucket_owner }}"
    shell: /bin/bash
    system: true

- name: home directory
  file:
    path: "{{ bitbucket_home }}"
    state: directory
    group: "{{ bitbucket_owner }}"
    owner: "{{ bitbucket_group }}"
    mode: 0750

- include: download.yml

- name: stop for upgrade, rollback or rollfoward
  service: name=bitbucket state=stopped
  when: bitbucket_lcm['operation'] in ['upgrade','rollback','rollforward']
  notify:
    - bitbucket-systemctl-daemon-reload
    - bitbucket-systemctl-restart

- include_tasks: database.yml
  when: bitbucket_database_inventory_hostname is defined and bitbucket_database_type == 'postgresql'

- include: install.yml

- include: configuration.yml

- include: jmx.yml
  when: bitbucket_jmx.enable

- name: Configure trusts
  include_role:
    name: c2platform.core.java
    tasks_from: main
  vars:
    java_version: bitbucket
    java_versions:
      bitbucket:
        install: no
        java_home: "{{ bitbucket_home_version_app }}/jre"
        keystore: "{{ bitbucket_home_version_app }}/jre/lib/security/cacerts"
        trusts: "{{ bitbucket_trusts }}"
        notify: bitbucket-systemctl-restart
  when: bitbucket_trusts is defined

- include: service.yml

- include: prepare.yml
  when: bitbucket_lcm['operation'] == 'prepare-upgrade'

- name: scripts directory
  file:
    path: "{{ bitbucket_scripts }}"
    state: directory
    group: "{{ bitbucket_owner }}"
    owner: "{{ bitbucket_group }}"
    mode: 0755

- include: jobs.yml
